# SPDX-License-Identifier: Apache-2.0
# Generated by k9x_studio on 2026-09-10 23:47:14

import yaml
from pathlib import Path
from typing import Any, Dict


class AgentLoader:
    """Merges per-agent YAML with the global config dict."""

    def __init__(self, agents_yaml_dir: Path):
        self._dir = Path(agents_yaml_dir)
        self._cache: Dict[str, dict] = {}

    def _load(self, agent_name: str) -> dict:
        if agent_name not in self._cache:
            snake = "_".join(
                p.lower() for p in __import__("re").sub(
                    r"([a-z0-9])([A-Z])", r"\1_\2",
                    __import__("re").sub(r"(.)([A-Z][a-z]+)", r"\1_\2", agent_name)
                ).split("_")
            )
            path = self._dir / f"{snake}.yaml"
            if path.exists():
                with open(path) as f:
                    self._cache[agent_name] = yaml.safe_load(f) or {}
            else:
                self._cache[agent_name] = {}
        return self._cache[agent_name]

    def merge_with_global(self, agent_name: str, global_config: dict) -> dict:
        merged = dict(global_config)
        merged.update(self._load(agent_name))
        return merged
