# SPDX-License-Identifier: Apache-2.0
# Generated by k9x_studio on 2026-09-10 23:47:14
# FinancialAnalysisAi — Entry point

import sys
import json
import time
import yaml
import textwrap
import logging
from pathlib import Path

from k9_aif_abb.k9_factories.llm_factory import LLMFactory
from k9_aif_abb.k9_factories.model_router_factory import ModelRouterFactory

from orchestrators.agn1_deterministic_rule_engine_orchestrator import Agn1DeterministicRuleEngineOrchestrator

from orchestrators.agn2_exception_resolution_agent_orchestrator import Agn2ExceptionResolutionAgentOrchestrator

from orchestrators.agn3_gl_coding_agent_orchestrator import Agn3GlCodingAgentOrchestrator

from orchestrators.agn4_anomaly_detection_agent_orchestrator import Agn4AnomalyDetectionAgentOrchestrator

from orchestrators.agn5_payment_optimization_agent_orchestrator import Agn5PaymentOptimizationAgentOrchestrator

from orchestrators.agn6_expense_audit_agent_orchestrator import Agn6ExpenseAuditAgentOrchestrator

from orchestrators.agn7_vendor_master_agent_orchestrator import Agn7VendorMasterAgentOrchestrator


logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)

CONFIG_PATH   = Path(__file__).parent / "config" / "config.yaml"
SQUADS_PATH   = Path(__file__).parent / "config" / "squads.yaml"
SCENARIO_PATH = Path(__file__).parent / "config" / "scenario.json"

_W = 66  # console width


def load_config(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def load_scenario(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path) as f:
        return json.load(f) or {}


def render_scenario_banner(scenario: dict, payload: dict) -> str:
    lines = []
    lines.append("=" * _W)
    lines.append("  Use Case Scenario")
    lines.append("=" * _W)
    if scenario.get("title"):
        lines.append(f"  {scenario['title']}")
        lines.append("─" * _W)
    if scenario.get("narrative"):
        for line in textwrap.wrap(scenario["narrative"], width=_W - 2):
            lines.append(f"  {line}")
        lines.append("")
    lines.append("  Input")
    lines.append("")
    for line in json.dumps(payload, indent=2, default=str).splitlines():
        lines.append(f"  {line}")
    lines.append("")
    lines.append("=" * _W)
    return "\n".join(lines)


def render_result_summary(result: dict, app_name: str, orch_name: str, elapsed_s: float, correlation_id: str) -> str:
    lines = []
    status = result.get("status", "unknown").upper()
    squad_id = result.get("squad_id", "—")

    lines.append("=" * _W)
    lines.append("  K9-AIF Execution Summary")
    lines.append("=" * _W)
    lines.append(f"  Project:        {app_name}")
    lines.append(f"  Orchestrator:   {orch_name}")
    lines.append(f"  Status:         {status}")
    lines.append(f"  Squad:          {squad_id}")
    lines.append(f"  Elapsed:        {elapsed_s:.2f}s")
    lines.append(f"  Correlation ID: {correlation_id}")
    lines.append("─" * _W)

    # ── Agent Results table ───────────────────────────────────────────
    skip = {"status", "squad_id"}
    agent_rows = [
        (k, v) for k, v in result.items()
        if k not in skip and isinstance(v, dict)
    ]

    if agent_rows:
        lines.append("")
        lines.append("  Agent Results")
        lines.append("")
        hdr = f"  {'Step':<5}  {'Agent':<28}  {'Status':<12}  {'Conf':>5}  {'Itr':>4}  {'Model'}"
        lines.append(hdr)
        lines.append("  " + "─" * (len(hdr) - 2))

        for step, (key, val) in enumerate(agent_rows, start=1):
            agent_name = val.get("agent", key)
            if len(agent_name) > 26:
                agent_name = agent_name[:23] + "..."

            if "iterations" in val:
                status_cell = val.get("disposition", "—")
                conf = f"{val.get('final_confidence', 0.0):.2f}"
                itr = str(val.get("iterations", "—"))
                model = "—"
            elif "rounds" in val:
                status_cell = val.get("disposition", "—")
                conf = f"{val.get('final_score', 0.0):.2f}"
                itr = str(val.get("rounds", "—"))
                model = "—"
            else:
                status_cell = "done"
                conf = "—"
                itr = "—"
                model = val.get("model_used", "—")

            lines.append(
                f"  {step:<5}  {agent_name:<28}  {status_cell:<12}  {conf:>5}  {itr:>4}  {model}"
            )

    # ── Execution Notes ───────────────────────────────────────────────
    lines.append("")
    lines.append("─" * _W)
    lines.append("  Execution Notes")
    lines.append("")

    warnings = []
    for key, val in agent_rows:
        agent_name = val.get("agent", key)
        label = key.replace("_", " ").title()

        if "iterations" in val:
            disp = val.get("disposition", "—")
            conf = val.get("final_confidence", 0.0)
            itr = val.get("iterations", 0)
            evidence = val.get("evidence", [])
            lines.append(f"  [{label}]  Validation Loop · {itr} iteration(s) · disposition={disp} · confidence={conf:.2f}")
            if conf < 0.8:
                warnings.append(f"{agent_name}: confidence {conf:.2f} below threshold 0.80 — implement evaluate_observation() for real domain scoring.")
            lines.append(f"    Evidence: {len(evidence)} observation(s) recorded")
            output = val.get("output", {}) if isinstance(val.get("output"), dict) else {}
            conclusion = str(output.get("conclusion", "")).strip()
            reasoning = str(output.get("reasoning", "")).strip()
            if conclusion:
                lines.append(f"    Conclusion: {textwrap.shorten(conclusion, width=120, placeholder='…')}")
            if reasoning:
                lines.append(f"    Reasoning:  {textwrap.shorten(reasoning, width=120, placeholder='…')}")
        elif "rounds" in val:
            disp = val.get("disposition", "—")
            score = val.get("final_score", 0.0)
            rounds = val.get("rounds", 0)
            critique_log = val.get("critique_log", [])
            lines.append(f"  [{label}]  Critic-Actor Loop · {rounds} round(s) · disposition={disp} · score={score:.2f}")
            if score < 0.8:
                warnings.append(f"{agent_name}: score {score:.2f} below threshold 0.80 — refine critique()/act() for real domain feedback.")
            lines.append(f"    Critiques: {len(critique_log)} round(s) recorded")
            output = val.get("output", {}) if isinstance(val.get("output"), dict) else {}
            summary = str(output.get("summary", "")).strip()
            draft = str(output.get("draft", "")).strip()
            if summary:
                lines.append(f"    Summary: {textwrap.shorten(summary, width=120, placeholder='…')}")
            if draft:
                lines.append(f"    Draft:   {textwrap.shorten(draft, width=120, placeholder='…')}")
        else:
            output = str(val.get("output", ""))
            snippet = textwrap.shorten(output, width=120, placeholder="…")
            lines.append(f"  [{label}]  {snippet}")

    if warnings:
        lines.append("")
        lines.append("  Warnings")
        for w in warnings:
            lines.append(f"  ⚠  {w}")

    lines.append("")
    lines.append("=" * _W)
    lines.append("  Tip: run with --json to print full result JSON")
    lines.append("=" * _W)
    return "\n".join(lines)


def main():
    raw_json = "--json" in sys.argv

    config = load_config(CONFIG_PATH)
    LLMFactory.bootstrap(config)
    ModelRouterFactory.get_router(config)

    log.info("=== FinancialAnalysisAi starting ===")


    orch_1 = Agn1DeterministicRuleEngineOrchestrator(config=config)
    orch_1.start(str(SQUADS_PATH))

    orch_2 = Agn2ExceptionResolutionAgentOrchestrator(config=config)
    orch_2.start(str(SQUADS_PATH))

    orch_3 = Agn3GlCodingAgentOrchestrator(config=config)
    orch_3.start(str(SQUADS_PATH))

    orch_4 = Agn4AnomalyDetectionAgentOrchestrator(config=config)
    orch_4.start(str(SQUADS_PATH))

    orch_5 = Agn5PaymentOptimizationAgentOrchestrator(config=config)
    orch_5.start(str(SQUADS_PATH))

    orch_6 = Agn6ExpenseAuditAgentOrchestrator(config=config)
    orch_6.start(str(SQUADS_PATH))

    orch_7 = Agn7VendorMasterAgentOrchestrator(config=config)
    orch_7.start(str(SQUADS_PATH))


    scenario = load_scenario(SCENARIO_PATH)

    payload = scenario.get("payload") or {
        "event_type": "finance",
        "query": "Sample request for FinancialAnalysisAi",
    }
    payload.setdefault("event_type", "finance")
    payload.setdefault("correlation_id", "test-001")

    if not raw_json and (scenario.get("title") or scenario.get("narrative")):
        print(render_scenario_banner(scenario, payload))

    log.info("Sending payload: %s", payload)


    _t0_1 = time.time()
    result_1 = orch_1.execute_flow(payload)
    _elapsed_1 = time.time() - _t0_1

    if raw_json:
        print("\n=== Result from Agn1DeterministicRuleEngineOrchestrator (JSON) ===")
        print(json.dumps(result_1, indent=2, default=str))
    else:
        print("\n" + render_result_summary(
            result_1,
            app_name="FinancialAnalysisAi",
            orch_name="Agn1DeterministicRuleEngineOrchestrator",
            elapsed_s=_elapsed_1,
            correlation_id=payload["correlation_id"],
        ))

    _t0_2 = time.time()
    result_2 = orch_2.execute_flow(payload)
    _elapsed_2 = time.time() - _t0_2

    if raw_json:
        print("\n=== Result from Agn2ExceptionResolutionAgentOrchestrator (JSON) ===")
        print(json.dumps(result_2, indent=2, default=str))
    else:
        print("\n" + render_result_summary(
            result_2,
            app_name="FinancialAnalysisAi",
            orch_name="Agn2ExceptionResolutionAgentOrchestrator",
            elapsed_s=_elapsed_2,
            correlation_id=payload["correlation_id"],
        ))

    _t0_3 = time.time()
    result_3 = orch_3.execute_flow(payload)
    _elapsed_3 = time.time() - _t0_3

    if raw_json:
        print("\n=== Result from Agn3GlCodingAgentOrchestrator (JSON) ===")
        print(json.dumps(result_3, indent=2, default=str))
    else:
        print("\n" + render_result_summary(
            result_3,
            app_name="FinancialAnalysisAi",
            orch_name="Agn3GlCodingAgentOrchestrator",
            elapsed_s=_elapsed_3,
            correlation_id=payload["correlation_id"],
        ))

    _t0_4 = time.time()
    result_4 = orch_4.execute_flow(payload)
    _elapsed_4 = time.time() - _t0_4

    if raw_json:
        print("\n=== Result from Agn4AnomalyDetectionAgentOrchestrator (JSON) ===")
        print(json.dumps(result_4, indent=2, default=str))
    else:
        print("\n" + render_result_summary(
            result_4,
            app_name="FinancialAnalysisAi",
            orch_name="Agn4AnomalyDetectionAgentOrchestrator",
            elapsed_s=_elapsed_4,
            correlation_id=payload["correlation_id"],
        ))

    _t0_5 = time.time()
    result_5 = orch_5.execute_flow(payload)
    _elapsed_5 = time.time() - _t0_5

    if raw_json:
        print("\n=== Result from Agn5PaymentOptimizationAgentOrchestrator (JSON) ===")
        print(json.dumps(result_5, indent=2, default=str))
    else:
        print("\n" + render_result_summary(
            result_5,
            app_name="FinancialAnalysisAi",
            orch_name="Agn5PaymentOptimizationAgentOrchestrator",
            elapsed_s=_elapsed_5,
            correlation_id=payload["correlation_id"],
        ))

    _t0_6 = time.time()
    result_6 = orch_6.execute_flow(payload)
    _elapsed_6 = time.time() - _t0_6

    if raw_json:
        print("\n=== Result from Agn6ExpenseAuditAgentOrchestrator (JSON) ===")
        print(json.dumps(result_6, indent=2, default=str))
    else:
        print("\n" + render_result_summary(
            result_6,
            app_name="FinancialAnalysisAi",
            orch_name="Agn6ExpenseAuditAgentOrchestrator",
            elapsed_s=_elapsed_6,
            correlation_id=payload["correlation_id"],
        ))

    _t0_7 = time.time()
    result_7 = orch_7.execute_flow(payload)
    _elapsed_7 = time.time() - _t0_7

    if raw_json:
        print("\n=== Result from Agn7VendorMasterAgentOrchestrator (JSON) ===")
        print(json.dumps(result_7, indent=2, default=str))
    else:
        print("\n" + render_result_summary(
            result_7,
            app_name="FinancialAnalysisAi",
            orch_name="Agn7VendorMasterAgentOrchestrator",
            elapsed_s=_elapsed_7,
            correlation_id=payload["correlation_id"],
        ))



if __name__ == "__main__":
    main()